
version: '20.10.8'

services:
  db:
    image: postgres:14.5
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
